# GitHub Sponsors - BlenderCivil
# Place this file at: .github/FUNDING.yml (in your repository root)

# GitHub Sponsors username (primary - no fees for personal sponsors!)
github: [DesertSpringsCivil]

# Alternative platforms (uncomment and add usernames as needed)
# patreon: your_patreon_username
# ko_fi: your_kofi_username
# open_collective: blendercivil

# Custom donation links (up to 4)
# custom: ["https://www.paypal.me/yourname", 
# "https://desertspringscivil.com/donate"]
